/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║          Self-Healing Locator Helper (Playwright JS)         ║
 * ║  Reads locators.json produced by locator_monitor.py and      ║
 * ║  returns the best available CSS selector for each element.   ║
 * ╚══════════════════════════════════════════════════════════════╝
 *
 * STATUS PRIORITY (what gets used):
 *   "healed"  → Scrapling found an adaptive match; uses generated selector
 *   "ok"      → Original selector still valid; uses original
 *   "missing" → Scrapling couldn't find the element; keeps original so test
 *               fails loudly instead of silently passing on the wrong element
 *
 * USAGE in a test:
 *   import { healedLocator, getSelector } from './helpers/healingLocator.js';
 *   const input = healedLocator(page, 'new_todo_input');
 *   await input.fill('Buy groceries');
 */

import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Path to the locators.json generated by locator_monitor.py */
const LOCATORS_FILE = path.resolve(__dirname, '../../locators.json');

/** In-memory cache to avoid re-reading the file on every locator call */
let   _cache     = null;
let   _cacheTime = 0;
const CACHE_TTL  = 60_000; // 60 s

// ─── HARDCODED FALLBACKS (mirrors WATCH_LIST in locator_monitor.py) ───────────
// Used when locators.json doesn't exist yet (e.g. first run, or CI without
// the Python monitor step).
const FALLBACKS = {
  // ASU Apply page
  hero_heading:         'h1.h1-large',
  view_app_details_btn: 'button.bg-secondary',
  mode_radio_group:     '#radio-mode-type',
  in_person_card:       "button[value='in-person']",
  online_card:          "button[value='online']",
  degree_card:          "button[value='DG']",
  nondegree_card:       "button[value='NDG']",
  continue_button:      "[data-cy='user-create-account-create-account-button']",
  sign_in_button:       ".btn-primary",
  app_details_section:  '#application-details',
  contact_email:        "a[href='mailto:admissions@asu.edu']",
  footer_services:      "[data-cy='default-footer-university-services-menu']",
};

// ─── STRUCTURAL-ELEMENT DENYLIST ──────────────────────────────────────────────
// If a "healed" selector points to one of these structural nodes it means the
// monitor ran without --js (HTTP fetcher got pre-render HTML) and the adaptive
// match is garbage.  Fall back to the known-good original instead.
const STRUCTURAL_SELECTORS = new Set([
  '#app', 'body', 'html', 'head', 'noscript', 'script',
  'body > noscript', 'head > script', 'head > link',
]);

function _isStructural(sel) {
  if (!sel) return false;
  if (STRUCTURAL_SELECTORS.has(sel.trim())) return true;
  // Catches variants like "head > script", "head > link:nth-of-type(2)", etc.
  return /^(head|body)\s*>/.test(sel.trim());
}

// ─── INTERNAL ─────────────────────────────────────────────────────────────────

/**
 * Read and cache locators.json.
 * Returns the `locators` sub-object, or null if the file is unavailable.
 *
 * @returns {Record<string, {original: string, current: string, status: string}> | null}
 */
function _loadLocators() {
  const now = Date.now();
  if (_cache && (now - _cacheTime) < CACHE_TTL) return _cache;

  try {
    const raw  = fs.readFileSync(LOCATORS_FILE, 'utf-8');
    const data = JSON.parse(raw);
    _cache     = data.locators ?? {};
    _cacheTime = now;
    return _cache;
  } catch (err) {
    // File missing or malformed → warn once, don't spam
    if (!_cache) {
      console.warn(
        `[HealingLocator] ⚠  Could not read ${LOCATORS_FILE}: ${err.message}\n` +
        `[HealingLocator]    Run "python locator_monitor.py" first, or tests will use hardcoded fallbacks.`
      );
    }
    return null;
  }
}

// ─── PUBLIC API ───────────────────────────────────────────────────────────────

/**
 * Return the best available CSS selector string for a named locator.
 *
 * @param {string} name  Key matching WATCH_LIST in locator_monitor.py
 * @returns {string}     CSS selector
 */
export function getSelector(name) {
  const locs  = _loadLocators();
  const entry = locs?.[name];

  if (!entry) {
    if (!FALLBACKS[name]) {
      console.warn(`[HealingLocator] ⚠  Unknown locator key: "${name}". Returning key as-is.`);
    }
    return FALLBACKS[name] ?? name;
  }

  switch (entry.status) {
    case 'ok':
      return entry.current;

    case 'healed': {
      if (_isStructural(entry.current)) {
        const fallback = FALLBACKS[name] ?? entry.original;
        console.warn(
          `[HealingLocator] ⚠  Healed selector for "${name}" looks like a structural element ` +
          `("${entry.current}") — monitor may have run without --js. ` +
          `Falling back to: "${fallback}"`
        );
        return fallback;
      }
      console.info(
        `[HealingLocator] 🔧 Healed selector for "${name}": ` +
        `"${entry.original}"  →  "${entry.current}"`
      );
      return entry.current;
    }

    case 'missing':
      console.error(
        `[HealingLocator] ❌ Locator "${name}" is MISSING on the page! ` +
        `Using original selector so the test fails explicitly.`
      );
      return entry.original;

    default:
      return entry.current ?? FALLBACKS[name] ?? name;
  }
}

/**
 * Return a Playwright Locator built from the self-healed selector.
 *
 * @param {import('@playwright/test').Page} page
 * @param {string} name  Key matching WATCH_LIST in locator_monitor.py
 * @returns {import('@playwright/test').Locator}
 */
export function healedLocator(page, name) {
  return page.locator(getSelector(name));
}

/**
 * Return a full health report array (for logging in beforeAll hooks).
 *
 * @returns {{ name: string, status: string, original: string, current: string }[]}
 */
export function getLocatorReport() {
  const locs = _loadLocators();
  if (!locs) return [];
  return Object.entries(locs).map(([name, info]) => ({
    name,
    status:   info.status,
    original: info.original,
    current:  info.current,
  }));
}

/**
 * Force-invalidate the in-memory cache (useful in long-running test sessions
 * if locators.json is updated mid-run).
 */
export function invalidateLocatorCache() {
  _cache     = null;
  _cacheTime = 0;
}
